version: 2
jobs:
  build_and_deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo ${GOOGLE_AUTH_JSON} > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup_remote_docker
      - run: 
          name: Docker build and push client
          command: |
            docker build --rm=false -t eu.gcr.io/${GOOGLE_PROJECT_ID}/client:$CIRCLE_SHA1 ./packages/client
            gcloud docker --verbosity=error -- push eu.gcr.io/${GOOGLE_PROJECT_ID}/client:$CIRCLE_SHA1
      - run: 
          name: Docker build and push server
          command: |
            docker build --rm=false -t eu.gcr.io/${GOOGLE_PROJECT_ID}/server:$CIRCLE_SHA1 ./packages/server
            gcloud docker --verbosity=error -- push eu.gcr.io/${GOOGLE_PROJECT_ID}/server:$CIRCLE_SHA1
      - run: 
          name: Deploy to Kubernetes
          command: |
            envsubst < ./deployment/frontend_deployment.yaml > ./deployment/frontend_deployment_patched.yaml
            envsubst < ./deployment/server_deployment.yaml > ./deployment/server_deployment_patched.yaml
            kubectl apply -f ./deployment

workflows:
  version: 2
  build:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
              - master
