apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: teamy
  template:
    metadata:
      labels:
        app: teamy
        tier: frontend
    spec:
      containers:
      - name: teamy
        image: eu.gcr.io/teamy-237708/client:65923c40d3fad2d3252fda3d9f9e964cf3e8ecb5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ENV
            value: production
        ports:
        - containerPort: 80
