apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: teamy
  template:
    metadata:
      labels:
        app: teamy
        tier: frontend
    spec:
      containers:
      - name: teamy
        image: eu.gcr.io/${GOOGLE_PROJECT_ID}/client:${CIRCLE_SHA1}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: BackendUri
            value: http://104.199.12.154:4000/
        ports:
        - containerPort: 80
