apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: teamy
  template:
    metadata:
      labels:
        app: teamy
        tier: backend
    spec:
      containers:
      - name: teamy
        image: eu.gcr.io/${GOOGLE_PROJECT_ID}/server:${CIRCLE_SHA1}
        resources:
          limits:
            memory: "328Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000