apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: teamy
  template:
    metadata:
      labels:
        app: teamy
        tier: backend
    spec:
      containers:
      - name: teamy
        image: eu.gcr.io/teamy-237708/server:196e1574c041ce823dfe23802ae51e178a1ae51c
        resources:
          limits:
            memory: "328Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000